version: '2'

services:
  node-api:
    container_name: node-api
    build: ./
    image: node:18
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./app:/usr/src/app
    links:
      - db

  db:
    image: mongo:4.2.2
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./data:/mongodata
